spring:
  profiles:
    active:
    - test
    
---

server:
  port: 8088

spring:
  profiles:
    test
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-total: 15
      max-wait-millis: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10
        max-active: 20
        min-idle: 5

logging:
  level: 
    com.gxf.webapi: debug
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.gxf.webapi.entities
---

server:
  port: 8080

spring:
  profiles:
    dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-total: 15
      max-wait-millis: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10
        max-active: 20
        min-idle: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.gxf.webapi.entities